---
- name: disable all repos
  ansible.builtin.command: subscription-manager repos --disable='*'

- name: enable repos
  ansible.builtin.command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ enable_repos_rhel8 }}"
