---
- name: Same as above but subscribe to a specific pool by ID.
  community.general.redhat_subscription:
    state: present
    username: "{{ rht_user }}"
    password: "{{ rht_pass }}"
    pool_ids: "{{ pool_ids }}"

- name: sleep 60 sec
  ansible.builtin.command: sleep 60
