---
- name: Launch instance
  amazon.aws.ec2_instance:
     aws_access_key: "{{ec2_access_key}}"
     aws_secret_key: "{{ec2_secret_key}}"
     key_name: "{{ keypair }}"
     instance_type: "{{ instance_type }}"
     image_id: "{{ image_rhel8 }}"
     region: "{{ region }}"
     vpc_subnet_id: "{{ subnet_id }}"
     security_group: "{{ security_group_id }}"
     network:
       assign_public_ip: yes
     tags:
       TowerManaged: True
     wait: true
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
