---
- name: Install packages
  yum: 
    name: firewalld
    state: present

- name: Enable nginx
  service: 
    name: firewalld.service
    state: started
    enabled: yes 

- name: Open nginx port
  firewalld:
    zone: public
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
